import deprecate from ember-deprecations
emberjs/data pull request #7406
Opened 2020-12-29 03:00 UTC by BryanCrotaz

2021-01-04 17:40 UTC, igorT commented
Do we need to add a dependency on ember-deprecations?

2021-01-04 17:48 UTC, BryanCrotaz commented
it used to be imported from @ember/debug, but that doesn't work any more.

2021-01-13 22:07 UTC, igorT commented
@BryanCrotaz my question is more, how come we import from `ember-deprecations` but don't add it to `package.json`?

2021-01-13 22:11 UTC, snewcomer commented
Also, do we have a link or RFC describing this change in behaviour?  I'm also unable to find this package.

It looks like this function is still around...

https://api.emberjs.com/ember/3.24/functions/@ember%2Fdebug/deprecate

2021-01-13 22:48 UTC, rwjblue requested changes

2021-01-13 22:48 UTC, rwjblue commented on packages/-ember-data/addon/setup-container.js
> -import { deprecate } from '@ember/debug';
The original import path is correct, we should not change it.

Can you explain what made you want to update?

2021-04-06 20:57 UTC, runspired commented
Concurring with @rwjblue import from `@ember/deprecate` is the correct location. https://api.emberjs.com/ember/3.25/functions/@ember%2Fdebug/deprecate

Some more context on the issue this was attempting to address in a bug ticket would be helpful if this has remained an issue for your app.

2021-04-06 20:57 UTC, closed without merging