Model state error 3.28
emberjs/data pull request #8154
Opened 2022-08-26 09:22 UTC by yratanov

Changed base branch from #8009 

Hey guys,

I faced a problem and did a test + added a fix, the simplest way to replicate:
```js
myModel = this.store.createRecord('my-model');
myModel.errors.add('fieldA', ['blank']);
myModel.errors.add('fieldB', ['blank']);
later(() => {
  set(myModel, 'fieldA', 'value');
  set(myModel, 'fieldB', 'value');
}, 1000);
```

It raises an error: 
```
Attempted to handle event `becameValid` on <my-model:null> while in state root.loaded.created.uncommitted.
```

I'm not sure why it is being raised only if there are 2 or more fields with errors.

2022-08-29 19:02 UTC, runspired requested changes
a little bit of test cleanup. Also both ember 3.24 and 3.20 scenarios fail, you'll want to run the tests with the appropriate ember-try scenarios to check why.

Annoying that TS seems to have drifted in a way that there are errors now there weren't before on 3.28 :'(  I suspect that's unrelated to 3.24/3.28 failing though.

2022-08-29 19:02 UTC, runspired commented on packages/-ember-data/tests/integration/model-errors-test.ts
> +    assert.dom('.error-list__error').hasText('the-error');
we should assert it is invalid here and that we have two unique errors

2022-08-29 19:02 UTC, runspired commented on packages/-ember-data/tests/integration/model-errors-test.ts
> +    assert.dom('.error-list__error').doesNotExist();
we should also assert it is valid here

2022-09-03 07:28 UTC, yratanov commented on packages/-ember-data/tests/integration/model-errors-test.ts
> +    const errors = get(this.tag, 'errors');
<img width="769" alt="image" src="https://user-images.githubusercontent.com/1536262/188260719-82f45c62-61d7-4234-aaf9-c24aa1b6eafb.png">

2022-09-03 08:11 UTC, yratanov commented
@runspired I've added more tests, I have no idea why 3.20 and 3.24 are failing...

2022-09-12 23:13 UTC, runspired approved these changes

2022-09-12 23:14 UTC, runspired commented on packages/-ember-data/tests/integration/model-errors-test.ts
> +    const errors = get(this.tag, 'errors');
TL;DR since `Model` is not typed you need to add the typings for `DSModel` into the type for `tag` on the context.

2022-09-12 23:26 UTC, merged